#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/depuracao/vim-rdoc.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-repeat.git",

  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tsaleh/vim-matchit.git",
  "git://github.com/vim-scripts/tComment.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/ervandew/supertab.git",
  "git://github.com/mileszs/ack.vim.git",
  "git://github.com/torandu/vim-bufexplorer.git",
  "git://github.com/vim-scripts/bufkill.vim.git",
  "git://github.com/wincent/Command-T.git",
  "git://github.com/vim-scripts/DirDiff.vim.git",
  "git://github.com/vim-scripts/errormarker.vim.git",
  "git://github.com/vim-scripts/genutils.git",
  "git://github.com/vim-scripts/highlight.vim.git",
  "git://github.com/vim-scripts/IndentAnything.git",
  "git://github.com/vim-scripts/multvals.vim.git",
  "git://github.com/vim-scripts/Rename.git",
  "git://github.com/vim-scripts/Rubytest.vim.git",
  "git://github.com/vim-scripts/Session-manager.git",
  "git://github.com/vim-scripts/taglist.vim.git",
  "git://github.com/vim-scripts/arpeggio.git",
  "git://github.com/altercation/vim-colors-solarized.git",
  "git://github.com/vim-scripts/VimExplorer.git",
  "git://github.com/ecomba/vim-ruby-refactoring.git",
  "git://github.com/othree/xml.vim.git",
  "git://github.com/vim-scripts/XmlPretty.git",
  "git://github.com/vim-scripts/IndexedSearch.git",
  "git://github.com/vim-scripts/jQuery.git",
]

vim_org_scripts = [
# ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
